/**
 * Agent Metrics Types
 *
 * Defines types for observability metrics exposed via events and AgentState.
 *
 * The metrics system provides comprehensive performance and usage tracking:
 *
 * **Turn-Level Metrics** (emitted per turn):
 * - `HumanTurnMetrics` - User speech duration, transcript length
 * - `AITurnMetrics` - Time to first token, time to audio, token count, sentence count, etc.
 * - Emitted with `human-turn:ended` and `ai-turn:ended` events
 *
 * **Session-Level Metrics** (aggregate, exposed via `AgentState.metrics`):
 * - `AgentMetrics` - Cumulative metrics for the entire session
 *   - Session duration and timing
 *   - Turn statistics (total, completed, interrupted, abandoned)
 *   - Latency averages (TTFT, TTA, turn duration)
 *   - Content totals (LLM tokens, user transcript chars, response chars)
 *   - Audio metrics (speech duration, audio chunks, samples)
 *   - Error tracking (total errors, errors by source)
 *
 * **Internal Tracking State**:
 * - `MetricsTrackingState` - Internal machine context for tracking timestamps and counters
 * - Used to compute metrics in real-time as the conversation progresses
 *
 * Metrics enable monitoring agent performance, identifying bottlenecks, and
 * tracking usage patterns for optimization and cost analysis.
 *
 * @module types/metrics
 */

/**
 * Metrics for a single human turn.
 *
 * Emitted with the `human-turn:ended` event to provide observability
 * into user speech characteristics.
 */
export interface HumanTurnMetrics {
  /** Duration of user speech in milliseconds (from speech start to speech end) */
  speechDuration: number;
  /** Character count of the final transcript */
  transcriptLength: number;
}

/**
 * Metrics for a single AI turn.
 *
 * Emitted with `ai-turn:ended` and `ai-turn:interrupted` events to provide
 * detailed observability into response generation and synthesis performance.
 */
export interface AITurnMetrics {
  /** Time from AI turn start to first LLM token in milliseconds (TTFT - Time To First Token) */
  timeToFirstToken: number;
  /** Time from first token to first complete sentence in milliseconds */
  timeToFirstSentence: number;
  /** Time from first sentence to first TTS audio chunk in milliseconds (TTA - Time To Audio) */
  timeToFirstAudio: number;
  /** Total duration from AI turn start to AI turn end in milliseconds */
  totalDuration: number;
  /** Number of tokens generated by the LLM */
  tokenCount: number;
  /** Number of complete sentences in the response */
  sentenceCount: number;
  /** Character count of the complete response text */
  responseLength: number;
  /** Number of TTS audio chunks produced */
  audioChunkCount: number;
  /** Total audio samples synthesized (for calculating audio duration) */
  totalAudioSamples: number;
  /** Whether this turn was interrupted by user */
  wasInterrupted: boolean;
}

/**
 * Session timing metrics.
 * Tracks when the agent started and how long it has been running.
 */
export interface SessionMetrics {
  /** Unix timestamp (milliseconds) when the agent started */
  startedAt: number;
  /** Current session duration in milliseconds */
  duration: number;
}

/**
 * Turn statistics.
 * Provides counts of different turn outcomes for the session.
 */
export interface TurnStatistics {
  /** Total number of turns (user messages) in the session */
  total: number;
  /** Number of turns completed successfully (full AI response) */
  completed: number;
  /** Number of turns interrupted by user */
  interrupted: number;
  /** Number of turns abandoned by turn detector (too short, noise, etc.) */
  abandoned: number;
}

/**
 * Aggregate latency metrics (averages across all completed turns).
 *
 * These metrics help measure the responsiveness of the voice AI system.
 * Lower values indicate better user experience.
 */
export interface LatencyMetrics {
  /** Average time to first LLM token in milliseconds (TTFT) */
  averageTimeToFirstToken: number;
  /** Average time to first TTS audio chunk in milliseconds (TTA) */
  averageTimeToFirstAudio: number;
  /** Average total turn duration in milliseconds (from user turn end to AI turn end) */
  averageTurnDuration: number;
}

/**
 * Aggregate content metrics (totals across all turns).
 *
 * Tracks the volume of content generated and processed during the session.
 */
export interface ContentMetrics {
  /** Total LLM tokens generated across all turns */
  totalLLMTokens: number;
  /** Total characters in all user transcripts */
  totalUserTranscriptChars: number;
  /** Total characters in all AI responses */
  totalResponseChars: number;
}

/**
 * Aggregate audio metrics (totals across all turns).
 *
 * Tracks audio processing volume and duration for the session.
 */
export interface AudioMetrics {
  /** Total user speech duration in milliseconds */
  totalUserSpeechDuration: number;
  /** Total agent speaking duration in milliseconds */
  totalAgentSpeakingDuration: number;
  /** Total number of TTS audio chunks produced */
  totalAudioChunks: number;
  /** Total audio samples synthesized (for calculating total audio duration) */
  totalAudioSamples: number;
}

/**
 * Error tracking metrics.
 *
 * Provides visibility into errors that occurred during the session,
 * grouped by provider source for easier debugging.
 */
export interface ErrorMetrics {
  /** Total number of errors across all providers */
  total: number;
  /** Errors grouped by provider source (STT, LLM, TTS, VAD) */
  bySource: Record<"stt" | "llm" | "tts" | "vad", number>;
}

/**
 * Complete aggregate metrics exposed via `AgentState.metrics`.
 *
 * Provides cumulative session statistics including timing, turn counts,
 * latency averages, content totals, audio metrics, and error tracking.
 *
 * Access via:
 * - `agent.getSnapshot().metrics` - Get current metrics snapshot
 * - `agent.subscribe((state) => { state.metrics })` - Subscribe to metrics updates
 *
 * @example
 * ```typescript
 * const state = agent.getSnapshot();
 * console.log("Session duration:", state.metrics.session.duration);
 * console.log("Total turns:", state.metrics.turns.total);
 * console.log("Avg time to first token:", state.metrics.latency.averageTimeToFirstToken);
 * ```
 */
export interface AgentMetrics {
  /** Session timing metrics (start time, duration) */
  session: SessionMetrics;
  /** Turn statistics (total, completed, interrupted, abandoned) */
  turns: TurnStatistics;
  /** Latency averages (TTFT, TTA, turn duration) */
  latency: LatencyMetrics;
  /** Content totals (tokens, characters) */
  content: ContentMetrics;
  /** Audio totals (duration, chunks, samples) */
  audio: AudioMetrics;
  /** Error tracking (total, by source) */
  errors: ErrorMetrics;
}

/**
 * Internal metrics state tracked in machine context.
 * Used to calculate turn-level and aggregate metrics.
 * Not exposed to users directly.
 */
export interface MetricsTrackingState {
  // Session
  sessionStartedAt: number | null;

  // Current turn timestamps
  humanTurnStartTime: number | null;
  humanTurnEndTime: number | null;
  humanSpeechDuration: number;
  humanTranscriptLength: number;

  // AI turn timestamps
  aiTurnStartTime: number | null;
  firstTokenTime: number | null;
  firstSentenceTime: number | null;
  firstAudioTime: number | null;
  aiTurnEndTime: number | null;

  // Current turn counters
  currentTokenCount: number;
  currentSentenceCount: number;
  currentResponseLength: number;
  currentAudioChunkCount: number;
  currentAudioSamples: number;

  // Aggregate totals (for calculating averages)
  totalTimeToFirstToken: number;
  totalTimeToFirstAudio: number;
  totalTurnDuration: number;
  completedTurnsForAverage: number;

  // Aggregate counters
  totalTurns: number;
  completedTurns: number;
  interruptedTurns: number;
  abandonedTurns: number;
  totalLLMTokens: number;
  totalUserTranscriptChars: number;
  totalResponseChars: number;
  totalUserSpeechDuration: number;
  totalAgentSpeakingDuration: number;
  totalAudioChunks: number;
  totalAudioSamples: number;
  errorsBySource: Record<"stt" | "llm" | "tts" | "vad", number>;
}

/**
 * Creates the initial metrics tracking state.
 */
export function createInitialMetricsState(): MetricsTrackingState {
  return {
    sessionStartedAt: null,
    humanTurnStartTime: null,
    humanTurnEndTime: null,
    humanSpeechDuration: 0,
    humanTranscriptLength: 0,
    aiTurnStartTime: null,
    firstTokenTime: null,
    firstSentenceTime: null,
    firstAudioTime: null,
    aiTurnEndTime: null,
    currentTokenCount: 0,
    currentSentenceCount: 0,
    currentResponseLength: 0,
    currentAudioChunkCount: 0,
    currentAudioSamples: 0,
    totalTimeToFirstToken: 0,
    totalTimeToFirstAudio: 0,
    totalTurnDuration: 0,
    completedTurnsForAverage: 0,
    totalTurns: 0,
    completedTurns: 0,
    interruptedTurns: 0,
    abandonedTurns: 0,
    totalLLMTokens: 0,
    totalUserTranscriptChars: 0,
    totalResponseChars: 0,
    totalUserSpeechDuration: 0,
    totalAgentSpeakingDuration: 0,
    totalAudioChunks: 0,
    totalAudioSamples: 0,
    errorsBySource: { stt: 0, llm: 0, tts: 0, vad: 0 },
  };
}
